"""
Example script to call the /get_all_routes FastAPI endpoint.

This demonstrates how to use the new endpoint that accepts raw JSON
with searchCriteria and loads structure.
"""

import json
import requests

# API endpoint
API_URL = "http://localhost:8000/get_all_routes"


def load_json_file(file_path: str) -> dict:
    """Load JSON file."""
    with open(file_path, 'r') as f:
        return json.load(f)


def call_get_all_routes(json_data: dict, include_trip_plans: bool = False):
    """Call the /get_all_routes endpoint with JSON data."""
    print(f"Sending request to {API_URL}...")
    print(f"Number of loads: {len(json_data.get('loads', []))}")
    print(f"Origin: {json_data.get('searchCriteria', {}).get('origin', {}).get('city', 'Unknown')}")
    if include_trip_plans:
        print("⚠️  Including detailed trip plans with Gemini AI (this may take longer)...")
    
    try:
        params = {'include_trip_plans': include_trip_plans} if include_trip_plans else {}
        response = requests.post(API_URL, json=json_data, params=params, timeout=600)  # Longer timeout for Gemini
        response.raise_for_status()
        
        result = response.json()
        
        print("\n" + "=" * 80)
        print("RESPONSE")
        print("=" * 80)
        print(f"Total routes found: {result['total_routes']}")
        print(f"Message: {result['message']}")
        
        if result['total_routes'] > 0:
            print(f"\nFirst 5 routes:")
            for i, route in enumerate(result['routes'][:5]):
                print(f"\nRoute {route['route_id']}:")
                print(f"  Total Distance: {route['total_distance']:.0f} miles")
                print(f"  Total Revenue: ${route['total_revenue']:.2f}")
                print(f"  Total Deadhead: {route['total_deadhead']:.0f} miles")
                print(f"  Number of Segments: {len(route['segments'])}")
                print(f"  Ends near destination: {route['ends_near_destination']}")
                
                for j, segment in enumerate(route['segments']):
                    print(f"    Segment {j+1}: {segment['origin']} → {segment['destination']}")
                    print(f"      Distance: {segment['distance_miles']:.0f} mi, Revenue: ${segment['revenue']:.2f}")
                    print(f"      Deadhead before: {segment['deadhead_before']:.1f} mi")
            
            if result['total_routes'] > 5:
                print(f"\n... and {result['total_routes'] - 5} more routes")
        
        # Display trip plans if available
        if result.get('trip_plans'):
            print("\n" + "=" * 80)
            print("DETAILED TRIP PLANS (Generated by Gemini AI)")
            print("=" * 80)
            for plan in result['trip_plans']:
                print(f"\n{'='*80}")
                print(f"TRIP PLAN FOR ROUTE {plan['route_id']}")
                print(f"{'='*80}")
                print(f"\nSummary:")
                print(plan['summary'])
                
                if plan.get('estimated_duration_hours'):
                    print(f"\nEstimated Duration: {plan['estimated_duration_hours']:.1f} hours")
                
                if plan.get('fuel_stops'):
                    print(f"\nRecommended Fuel Stops:")
                    for stop in plan['fuel_stops']:
                        print(f"  - {stop}")
                
                if plan.get('rest_stops'):
                    print(f"\nRecommended Rest Stops:")
                    for stop in plan['rest_stops']:
                        print(f"  - {stop}")
                
                if plan.get('potential_issues'):
                    print(f"\nPotential Issues:")
                    for issue in plan['potential_issues']:
                        print(f"  ⚠️  {issue}")
                
                if plan.get('recommendations'):
                    print(f"\nRecommendations:")
                    for rec in plan['recommendations']:
                        print(f"  💡 {rec}")
                
                print(f"\nFull Detailed Plan:")
                print("-" * 80)
                print(plan['detailed_plan'])
                print("-" * 80)
        
        # Save full response to file
        with open('all_routes_response.json', 'w') as f:
            json.dump(result, f, indent=2)
        print(f"\n✓ Full response saved to all_routes_response.json")
        
        return result
        
    except requests.exceptions.ConnectionError:
        print("Error: Could not connect to the API.")
        print("Make sure the FastAPI server is running:")
        print("  uvicorn main:app --reload")
    except requests.exceptions.HTTPError as e:
        print(f"HTTP Error: {e}")
        print(f"Response: {response.text}")
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()


def main():
    import sys
    
    # Default file
    input_file = 'boston-dallas-20.json'
    include_trip_plans = False
    
    if len(sys.argv) > 1:
        input_file = sys.argv[1]
    
    # Check for --with-plans flag
    if '--with-plans' in sys.argv or '-p' in sys.argv:
        include_trip_plans = True
        print("⚠️  Gemini AI trip planning enabled (requires GEMINI_API_KEY)")
    
    print(f"Loading {input_file}...")
    try:
        json_data = load_json_file(input_file)
        
        # Validate structure
        if 'searchCriteria' not in json_data:
            print("Error: JSON must contain 'searchCriteria'")
            return
        
        if 'loads' not in json_data:
            print("Error: JSON must contain 'loads' array")
            return
        
        # Optionally limit number of loads for testing
        if len(sys.argv) > 2:
            try:
                max_loads = int(sys.argv[2])
                json_data['loads'] = json_data['loads'][:max_loads]
                print(f"Limiting to first {len(json_data['loads'])} loads for testing...")
            except ValueError:
                pass
        
        call_get_all_routes(json_data, include_trip_plans=include_trip_plans)
        
    except FileNotFoundError:
        print(f"Error: Could not find {input_file}")
        print(f"Usage: python3 example_get_all_routes.py [input_file.json] [max_loads] [--with-plans]")
        print(f"\nOptions:")
        print(f"  --with-plans or -p: Include detailed trip plans using Gemini AI")
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()

